[package]
name = "spotlight"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.31", features = ["default"] }
egui = "0.31"
global-hotkey = "0.6"
image = "0.25"
parking_lot = "0.12"
winreg = { version = "0.52", optional = true }

[target.'cfg(windows)'.dependencies]
winreg = "0.52"
